development: &default
  adapter: postgresql
  database: mydockerapp_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: <%= ENV['MYDOCKERAPP_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['MYDOCKERAPP_DB_1_PORT_5432_TCP_PORT'] %>

test:
  <<: *default
  database: mydockerapp_test
